### ISSUE TITLE
Timing error in recent versions.

### ISSUE THREAD

**Issue by tmd-set** [openrisc/or1k-src#10]
I found this error two months ago but I couldn't open an issue at that time so I wrote it on opencores.org under the nickname meitoku. 

Source: http://opencores.org/forum,OpenRISC,0,5489 

"Some programs that use timer works well with toochain versions before April 2014 now behave erratically. 
Example: timer.c in https://github.com/juliusbaxter/orconf2013/blob/master/sw/timer/timer.c. It is a led counter, but now with the latest or1k-gcc commit (at that time is [62a1a271e5fecc9fecdfc0961f76fdfddf43d6a7](https://github.com/openrisc/or1k-gcc/commit/62a1a271e5fecc9fecdfc0961f76fdfddf43d6a7)), the timer didn't work, first one led turned on, then all the led flashed immediately. When I switched to commit [d2093f8f4d182be22b24b459badd9f555859cc6f](https://github.com/openrisc/or1k-gcc/commit/d2093f8f4d182be22b24b459badd9f555859cc6f) of or1k-gcc and commit [7d53ef07ae838a707e2ca8a467e51cd1174cf388](https://github.com/openrisc/or1k-src/commit/7d53ef07ae838a707e2ca8a467e51cd1174cf388) of or1k-src, I got no such problem."

@wallento told me that this error was caused by a modification in or1k-src.

**Comment by bluecmd** [comment]
Could you try to bisect this and find the commit which caused the regression?

**Comment by tmd-set** [comment]
That error might be caused by a commit in 04/2014 or 05/2014 because at the time I posted that topic, I was working with this commit [8106050fa3112162b0dc27f5d7ea8ff62a1b03b1](https://github.com/openrisc/or1k-src/commit/8106050fa3112162b0dc27f5d7ea8ff62a1b03b1).

**Comment by bluecmd** [comment]
Sorry, maybe I wasn't clear. Please bisect down to a single commit.

**Comment by wallento** [comment]
Can you please compare whether the error exists with b50a0677685f4019ac4c7bb1cde778b0382fceb7 and 8f9b47e5d6c709c2839d238a988cd1509fb7c22f?

**Comment by wallento** [comment]
Hi,

I checked it now. The problem is Julius' code manually does the timer handling, while the recent changes made the timer more flexible. I added the use of the global timer period in 925d7f863b3579a4650fd91265ea6df48eaa69cc and tested it, it should work again now. The better way to use is or1k_timer_reset() now, see: http://pastie.org/9485187

Thanks for your feedback,
Stefan

**Comment by wallento** [comment]
You can find a prebuilt version for /opt/or1k-toolchain at http://lis.ei.tum.de/pub-download/optimsoc/toolchain/or1k-toolchain-20140819.tgz
