### ISSUE TITLE
Question for or1k timer control

### ISSUE THREAD

**Issue by minjiexm** [openrisc/or1k-src#16]
hi,
When I try to use timer related function in or1k-support.h, there are few lines demo which I paste below:
void tick_handler(void) {
  // Make schedule decision
  // and set new thread
  or1k_timer_reset();
  // End of exception, new thread will run
}
int main() {
  // Configure operating system and start threads..
  // Configure timer
  or1k_timer_init(50);
  or1k_timer_set_handler(&tick_handler);
  or1k_timer_set_mode(SPR_TTMR_SR);
  or1k_timer_enable();
  // Schedule first thread and die..
}

But I can not find define of SPR_TTMR_SR used by or1k_timer_set_mode function.
  or1k_timer_set_mode(SPR_TTMR_SR);

I tried to get SPR_TTMR_SR define from a file called spr-defs.h in mor1k-env-dev github
#define SPR_TTMR_SR  0x80000000 /*Signle Run*/
#define SPR_TTMR_CR  0xC0000000 /*Continuous Run*/
But it does not work at all.

So where I can get the right define of SPR_TTMR_SR used by or1k-support.h?

Thanks.

**Comment by wallento** [comment]
Hi @minjiexm,

I think this repo is kind of outdated because nearly all code has been upstreamed to the actual projects. Please check newlib and our build instructions: https://openrisc.io/newlib/

@skristiansson @stffrdhrn @juliusbaxter @olofk we don't need or1k-src anymore, right?

Cheers,
Stefan

**Comment by stffrdhrn** [comment]
It's mostly upstream. The one thing that is not is the site.exp file.

But I have a copy of it in my or1k-utils repo.

**Comment by minjiexm** [comment]
hi, wallento:

Thanks for the comments.

As you mentioned,  I am following https://openrisc.io/newlib/building.html to build my or1k toolchains.
Now I try to follow the doc for interrupt from below link:
https://openrisc.io/newlib/docs/html/group__or1k__interrupts.html.
The example is also copied from that link.
I can not get a clear picture for the function or1k_timer_set_mode(SPR_TTMR_SR);

Do you want me to open this issue to newlib?

Thanks.

**Comment by wallento** [comment]
Yes, please open it there. Thanks!
